config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_many :ingredients
	  has_many :directions
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
   accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
   validates_presence_of :title , :description
 has_attached_file :image, styles: { medium: "400x400>" }, validate_media_type: false
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show ,:edit ,:update , :destroy]
	def index
		@recipe = Recipe.all.order("created_at DESC")
	end
	def show

	end
	def new
		@recipe = Recipe.new
	end

	def create
	   @recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe, notice: "Sucessfully Created New Recipe"
		else
			render 'new'
		end
	end
	def edit
	end
	def update
		if @recipe.update_attributes(recipe_params)
			redirect_to @recipe
		else
			render "edit"
		end
	end
		def destroy
			@recipe.destroy
			redirect_to root_path, notice: "Sucessfully Deleted The Recipe"
		end

	private
	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes:[:id, :name, :_destroy], directions_attributes: [:id,:steps,:_destroy])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %head 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "The Mohanty's", root_path

    %ul.nav.navbar-nav.navbar-right
      %li= link_to "New Recipe", new_recipe_path
      %li= link_to "Sign Out", root_path, method: :delete
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

  = yield

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
  - if @recipe.errors.any?
    #errors
      %p
        = @recipe.errors.count
        Prevented this recipe froms saving
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, input_html: { class: 'form-control' }
    = f.input :image, input_html: { class: 'form-control' }

  = f.button :submit, class: "btn btn-primary"

app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render "form"

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
	.row
		- recipes.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do
							= image_tag recipe.image.url(:medium)
					%h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe
= render "form"

%br/

= link_to "Back" , root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title
				%p.description= @recipe.description



= link_to "back", root_path, class: "btn btn-default"
= link_to "edit", edit_recipe_path, class: "btn btn-default"
= link_to "delete", recipe_path , method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-default"